---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app-oauth2-proxy
  namespace: security
spec:
  interval: 15m
  chart:
    spec:
      chart: oauth2-proxy
      version: "6.10.1"
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
        namespace: flux-system
  maxHistory: 3
  values:
    replicaCount: 3
    podAnnotations:
      secret.reloader.stakater.com/reload: app-oauth2-proxy
    image:
      repository: quay.io/oauth2-proxy/oauth2-proxy
      tag: v7.4.0
    extraArgs:
      provider: github
      github-org: "LDS-Home"
      github-team: "lds-home-team"
      cookie-expire: 168h0m0s
      email-domain: "*"
      whitelist-domain: ".${SECRET_DOMAIN}"
      cookie-domain: ".${SECRET_DOMAIN}"
    config:
      existingSecret: app-oauth2-proxy
    service:
      main:
        ports:
          http:
            port: 4180
          metrics:
            port: 44180
            enabled: true
    probes:
      liveness: &probes
        enabled: false
    # ingress:
    #   main:
    #     enabled: true
    #     ingressClassName: nginx
    #     annotations:
    #       external-dns.alpha.kubernetes.io/target: ipv4.lildrunkensmurf.com
    #       nginx.ingress.kubernetes.io/whitelist-source-range: |
    #         10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
    #     hosts:
    #       - host: &host auth.lildrunkensmurf.com
    #         paths:
    #           - path: /oauth2
    #             pathType: Prefix
    #     tls:
    #       - hosts:
    #           - *host
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 105Mi
